### ISSUE TITLE
Input Field Issue - Unable to Reset Invalid Values

### ISSUE THREAD

**Issue by freedompraise** [freedompraise/25-5_clock#18]
## Description:
I've encountered an issue in the Session, and Break components of our project. When users input invalid values (not a valid number or outside the range of 5 to 40) into the session length input field, the field should reset to the current session length value, but it's not working as expected.

## Steps to Reproduce:
- Navigate to the Session or Break component.
- Attempt to enter an invalid value (e.g., "abc" or "50") into the session length input field.
- Observe that the input field does not reset as expected.

## Expected Behavior:
The input field should reset to the current session length value when an invalid input is entered.

**Comment by StrixV54** [comment]
Hi @freedompraise , checking this on my side if I can fix this.

**Comment by freedompraise** [comment]
> Hi @freedompraise , checking this on my side if I can fix this.

Alright, great!

**Comment by StrixV54** [comment]
@freedompraise You can check now looks gud to me

**Comment by StrixV54** [comment]
We can connect on Github. I will surely help you with other issues.

**Comment by freedompraise** [comment]
> @freedompraise You can check now looks gud to me

Alright, I'd review it

**Comment by freedompraise** [comment]
> We can connect on Github. I will surely help you with other issues.

It'd be my pleasure to connect
